package ch.adesso.dbextractor.core;

import java.sql.Connection;
import java.sql.SQLException;

import javax.sql.DataSource;

public class DbSupportH2 extends AbstractDbSupportSql92 implements DbSupport {

	public static final String DRIVER_CLASS_NAME = "org.h2.Driver";

	private static final String SQL_SELECT_PRIMARY_KEY_V1 = "SELECT CURRENT_CATALOG, CURRENT_SCHEMA, \r\n"
			+ "  c.CONSTRAINT_CATALOG, c.CONSTRAINT_SCHEMA, c.CONSTRAINT_NAME, \r\n"
			+ "  a.TABLE_CATALOG, a.TABLE_SCHEMA, a.TABLE_NAME, a.COLUMN_NAME, a.ORDINAL_POSITION \r\n"
			+ "FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS  c \r\n"
			+ "  INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE  a ON a.CONSTRAINT_CATALOG = c.CONSTRAINT_CATALOG AND a.CONSTRAINT_SCHEMA = c.CONSTRAINT_SCHEMA AND a.CONSTRAINT_NAME = c.CONSTRAINT_NAME \r\n"
			+ "                                                   AND a.TABLE_CATALOG = c.TABLE_CATALOG AND a.TABLE_SCHEMA = c.TABLE_SCHEMA AND a.TABLE_NAME = c.TABLE_NAME \r\n"
			+ "WHERE c.CONSTRAINT_TYPE = 'PRIMARY KEY' \r\n"
			+ "ORDER BY c.CONSTRAINT_CATALOG, c.CONSTRAINT_SCHEMA, c.CONSTRAINT_NAME, a.ORDINAL_POSITION";

	private static final String SQL_SELECT_FOREIGN_KEY_V1 = "SELECT CURRENT_CATALOG, CURRENT_SCHEMA, \r\n"
			+ "  c.CONSTRAINT_CATALOG, c.CONSTRAINT_SCHEMA, c.CONSTRAINT_NAME, \r\n"
			+ "  r.FKTABLE_CATALOG, r.FKTABLE_SCHEMA, r.FKTABLE_NAME, r.FKCOLUMN_NAME, \r\n"
			+ "  r.PKTABLE_CATALOG, r.PKTABLE_SCHEMA, r.PKTABLE_NAME, r.PKCOLUMN_NAME \r\n"
			+ "FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS         c \r\n"
			+ "  INNER JOIN INFORMATION_SCHEMA.CROSS_REFERENCES  r ON r.FKTABLE_CATALOG = c.CONSTRAINT_CATALOG AND r.FKTABLE_SCHEMA = c.CONSTRAINT_SCHEMA AND r.FK_NAME = c.CONSTRAINT_NAME \r\n"
			+ "WHERE c.CONSTRAINT_TYPE = 'FOREIGN KEY' \r\n"
			+ "ORDER BY c.CONSTRAINT_CATALOG, c.CONSTRAINT_SCHEMA, c.CONSTRAINT_NAME, r.ORDINAL_POSITION";

	private static final String SQL_SELECT_PRIMARY_KEY_V2 = "SELECT CURRENT_CATALOG, CURRENT_SCHEMA, \r\n"
			+ "  c.CONSTRAINT_CATALOG, c.CONSTRAINT_SCHEMA, c.CONSTRAINT_NAME, \r\n"
			+ "  a.TABLE_CATALOG, a.TABLE_SCHEMA, a.TABLE_NAME, a.COLUMN_NAME, a.ORDINAL_POSITION \r\n"
			+ "FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS  c \r\n"
			+ "  INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE  a ON a.CONSTRAINT_CATALOG = c.CONSTRAINT_CATALOG AND a.CONSTRAINT_SCHEMA = c.CONSTRAINT_SCHEMA AND a.CONSTRAINT_NAME = c.CONSTRAINT_NAME \r\n"
			+ "                                                   AND a.TABLE_CATALOG = c.TABLE_CATALOG AND a.TABLE_SCHEMA = c.TABLE_SCHEMA AND a.TABLE_NAME = c.TABLE_NAME \r\n"
			+ "WHERE c.CONSTRAINT_TYPE = 'PRIMARY KEY' \r\n"
			+ "ORDER BY c.CONSTRAINT_CATALOG, c.CONSTRAINT_SCHEMA, c.CONSTRAINT_NAME, a.ORDINAL_POSITION";

	private static final String SQL_SELECT_FOREIGN_KEY_V2 = "SELECT CURRENT_CATALOG, CURRENT_SCHEMA, \r\n"
			+ "  c.CONSTRAINT_CATALOG, c.CONSTRAINT_SCHEMA, c.CONSTRAINT_NAME, \r\n"
			+ "  fc.TABLE_CATALOG AS FKTABLE_CATALOG, fc.TABLE_SCHEMA AS FKTABLE_SCHEMA, fc.TABLE_NAME AS FKTABLE_NAME, fc.COLUMN_NAME AS FKCOLUMN_NAME, \r\n"
			+ "  a.TABLE_CATALOG AS PKTABLE_CATALOG, a.TABLE_SCHEMA AS PKTABLE_SCHEMA, a.TABLE_NAME AS PKTABLE_NAME, a.COLUMN_NAME AS PKCOLUMN_NAME \r\n"
			+ "FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS                c \r\n"
			+ "  INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE        fc ON fc.CONSTRAINT_CATALOG = c.CONSTRAINT_CATALOG AND fc.CONSTRAINT_SCHEMA = c.CONSTRAINT_SCHEMA AND fc.CONSTRAINT_NAME = c.CONSTRAINT_NAME \r\n"
			+ "                                                          AND fc.TABLE_CATALOG = c.TABLE_CATALOG AND fc.TABLE_SCHEMA = c.TABLE_SCHEMA AND fc.TABLE_NAME = c.TABLE_NAME \r\n"
			+ "  INNER JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS  r ON r.CONSTRAINT_CATALOG = c.CONSTRAINT_CATALOG AND r.CONSTRAINT_SCHEMA = c.CONSTRAINT_SCHEMA AND r.CONSTRAINT_NAME = c.CONSTRAINT_NAME \r\n"
			+ "  INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE         a ON a.CONSTRAINT_CATALOG = r.UNIQUE_CONSTRAINT_CATALOG AND a.CONSTRAINT_SCHEMA = r.UNIQUE_CONSTRAINT_SCHEMA AND a.CONSTRAINT_NAME = r.UNIQUE_CONSTRAINT_NAME AND a.ORDINAL_POSITION = fc.POSITION_IN_UNIQUE_CONSTRAINT \r\n"
			+ "WHERE c.CONSTRAINT_TYPE = 'FOREIGN KEY' \r\n"
			+ "ORDER BY c.CONSTRAINT_CATALOG, c.CONSTRAINT_SCHEMA, c.CONSTRAINT_NAME, fc.POSITION_IN_UNIQUE_CONSTRAINT";

	public DbSupportH2(DataSource dataSource) {
		super(dataSource);
	}

	@Override
	protected String getSqlSelectPrimaryKey(Connection con) throws SQLException {
		if (con.getMetaData().getDriverMajorVersion() == 1) {
			return SQL_SELECT_PRIMARY_KEY_V1;
		}
		return SQL_SELECT_PRIMARY_KEY_V2;
	}

	@Override
	protected String getSqlSelectForeignKey(Connection con) throws SQLException {
		if (con.getMetaData().getDriverMajorVersion() == 1) {
			return SQL_SELECT_FOREIGN_KEY_V1;
		}
		return SQL_SELECT_FOREIGN_KEY_V2;
	}

	@Override
	protected String toSqlValueString(byte[] value) {
		StringBuilder sb = new StringBuilder(value.length * 2 + 3);
		sb.append("X'");
		for (byte b : value) {
			sb.append(String.format("%02x", b));
		}
		sb.append("'");
		return sb.toString();
	}

}
