language: java
addons:
  sonarcloud:
    organization: "adesso-schweiz-ag"
    token:
      secure: "DBVgty2nd4kq6fvtk5Ln8T3UuXmhqZFv/Ro45ydj1qVg2U2uuHNDkI2x8jkuA/ttROo3Hgac4EDHzKy+7If2dRkb5TSXLYIk6iUnjMRWRLbQEfc3ySbNYWLOKoppt7KJb4v9sui8EIjwGldNbrxaelVjXuGB5VGDc7R0phWKB+ZDFI6XLMQ9nGSYJ1XJMZIEpURbe4tY3m/7tD8W6RscbJcCrc5n9fqeThDr7g/3wjiY90pEGmATcdtoFy5heUTzQFMefo3Vb6lHJ4mgQKN6Vn2JLCUIar0c7I/F5IUfirZ20SSOdx77s8aLQ1w/S7dWXYHmUGxgv0rkOq4/F1Haq5FoxAjnApvqtlA9GS9ctE2Pxq/gW8N+SZ7YvloSh190qPnt1PHV1OrFQHqphPWAQoWfpdIgpXoTKvBDZYpI/t346h0Wczw513jIOD2KImFZjG12KoXEeliJsWgzOxGNy4x+Sxxxt/PTJXnMMZGiqGmQ9OVxgs74uE1oshkYe+C+QtgzjPTlFypaxUYPDvltys96wEk6ueP7kJUB0M6jfn5G17omqqc8hNNQtET7R2+pcZBurAo2TS6iEffp5JMA9847puaLPCAgQUI7/v1YfkquKIn/wuwsY7P7NjIECnwphDa1P4TvU5gSzkzkUygSmi+qsf93CY6UBnvUn6oJuvA="
cache:
  directories:
    - $HOME/.m2/repository
install: true
script:
  - mvn clean verify sonar:sonar
deploy:
  provider: releases
  api_key:
    secure: MQXH58dqx8VCZOmtcTWipAvRBjU3WdyJhncpXCRCy6THvYKErb6rnyqfGEkfvS82Hnhbl9nlH9JGc09C6CjGzjb08gQAQ6L6riOysB83kmnFIlT9TExLPQLE70xqq/MTbpGtC0RnPBmtOOmvvnbcMKVDhtmUvV0h5WMq5U2vNa0jfqHzc1h9LVQP51MhYRr5nNyAAEJcPvKe0GokbJlm/kGQP6sElWjpChrJU7247sAc69+yoJlZMVqedbQcWGvuzJNko/m/XCTScCqrS6hkPuupa00HfRUfdM2ak/VFnRu2HqQuWq84wOLlLmItXPV3OT6n5ybNOBm5oclGIkkSrf368Z91bpI8vvnMVhZOKT5G26XDPH+o5hTd4SHeHSBvrvtkL8cZGX3O+oAaIzmhLuH0L8UjGSBOcKbYr062U1VYJoYW+/6Fep4NbAsOi2UHu1nvHv46JO+FEgaQmwZ8Xy1P63GuVet5SloLqX1Z9nTPxTxVBmNGQGt0nNZ2Cf6V2REuo1TA1L6KYmxqreggxAnTSQVZSPpzlvPPL0+7NytOIU1HhIC/vd+CcghmqnHpONZQGaVshz9NojX24/Md+ArXOylkA1+58bPVZXHSIz5PM2k600Cs6HLGrICuYpFEJNaNeKIY5eNTsLuad3x601/b4Opv+ylcU0pLZEhpf0c=
  draft: true
  file_glob: true
  file:
    - db-extractor-core/target/db-extractor-core-*.jar
	- db-extractor-core/target/db-extractor-core-*-sources.jar
  skip_cleanup: true
  on:
    repo: adessoSchweizAG/db-extractor
    tags: true