language: java
os: linux
dist: xenial
env:
  global:
    # travis login --pro --github-token <github-token> && travis encrypt -r adessoSchweizAG/db-extractor --pro GITHUB_TOKEN="<github-token>"
    - secure: "hCyHjqlQXbRX8w5tv4I/21KZvP8Hn4knFmFEv6ljanZSXmUj8VZD4+zc7jlFlaBUbgtDWhe9FZ4v1AqTX3NF6yk4mxHlonkYfBg3zdaSQtGesEgsH+TItFq3fFTfllIAYhoZYlDO4VT06vYobDlnXhoPLh9J4lTBh2/pjHfWGJeHgp21GWe2hva6C0xNPGNaWPKu+OInW+4mNoA0+bhBTuc0e0hoEhxH0YDwRVinZZo34OoXX+3/Bt+Q+HWSbrEFCVz60vDg3CAIYJbtqGtu+B0ZIWFn+YbYopFirm5Yn1ewUWM9hUhQPwe12bVo6diprvMZZVFxZynq6V2rn+eEFna9XwnfjrIaa1nJk6gzzprg2CPvRFRLHWEczzKN8zuN7D4GpsVg2W+U/tX8COFhRG6N4ERgOvo5anq6ZOGp6Ryr47s4y4h0iY7fSfOrjzbPlGKZLa+U4oSqJ3/yCod8Kb/VeNoSVhqVKscaI8C5tl8FK5l7WNbYi46Ls1ty+Wr5AujHAcsUqElZ0i62y403xyLN6tFZvAg26KWk5HeFCC59G6xCUj6cezSPTkwPJNNh0mkACEYLOUeS9O4pITPsIMVT2f5hAb8M4qFGtZKgGTTjnIFNiDUESc0hLl06lrwrJihdS6vVKtmRPoo5kDPMidhghU8DLWFAleSJ6IqWxcc="
services:
  - mysql
  - postgresql
addons:
  sonarcloud:
    organization: "adesso-schweiz-ag"
    token:
      secure: "DBVgty2nd4kq6fvtk5Ln8T3UuXmhqZFv/Ro45ydj1qVg2U2uuHNDkI2x8jkuA/ttROo3Hgac4EDHzKy+7If2dRkb5TSXLYIk6iUnjMRWRLbQEfc3ySbNYWLOKoppt7KJb4v9sui8EIjwGldNbrxaelVjXuGB5VGDc7R0phWKB+ZDFI6XLMQ9nGSYJ1XJMZIEpURbe4tY3m/7tD8W6RscbJcCrc5n9fqeThDr7g/3wjiY90pEGmATcdtoFy5heUTzQFMefo3Vb6lHJ4mgQKN6Vn2JLCUIar0c7I/F5IUfirZ20SSOdx77s8aLQ1w/S7dWXYHmUGxgv0rkOq4/F1Haq5FoxAjnApvqtlA9GS9ctE2Pxq/gW8N+SZ7YvloSh190qPnt1PHV1OrFQHqphPWAQoWfpdIgpXoTKvBDZYpI/t346h0Wczw513jIOD2KImFZjG12KoXEeliJsWgzOxGNy4x+Sxxxt/PTJXnMMZGiqGmQ9OVxgs74uE1oshkYe+C+QtgzjPTlFypaxUYPDvltys96wEk6ueP7kJUB0M6jfn5G17omqqc8hNNQtET7R2+pcZBurAo2TS6iEffp5JMA9847puaLPCAgQUI7/v1YfkquKIn/wuwsY7P7NjIECnwphDa1P4TvU5gSzkzkUygSmi+qsf93CY6UBnvUn6oJuvA="
cache:
  directories:
    - $HOME/.m2/repository
    - db-extractor/db-extractor-ui/src/main/js/frontend/node_modules
install: true
before_script:
  - mysql -e 'CREATE DATABASE demo;'
  - git config remote.origin.fetch "+refs/heads/master:refs/remotes/origin/master"
  - git fetch
script:
  - mvn clean verify sonar:sonar
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_EVENT_TYPE" = "push" ]; then mvn deploy -s .travis/settings.xml -pl db-extractor-core,db-extractor-spring -am; fi
before_deploy:
  - export MVN_PROJECT_VERSION=$(mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q)
deploy:
  provider: releases
  api_key:
    secure: MQXH58dqx8VCZOmtcTWipAvRBjU3WdyJhncpXCRCy6THvYKErb6rnyqfGEkfvS82Hnhbl9nlH9JGc09C6CjGzjb08gQAQ6L6riOysB83kmnFIlT9TExLPQLE70xqq/MTbpGtC0RnPBmtOOmvvnbcMKVDhtmUvV0h5WMq5U2vNa0jfqHzc1h9LVQP51MhYRr5nNyAAEJcPvKe0GokbJlm/kGQP6sElWjpChrJU7247sAc69+yoJlZMVqedbQcWGvuzJNko/m/XCTScCqrS6hkPuupa00HfRUfdM2ak/VFnRu2HqQuWq84wOLlLmItXPV3OT6n5ybNOBm5oclGIkkSrf368Z91bpI8vvnMVhZOKT5G26XDPH+o5hTd4SHeHSBvrvtkL8cZGX3O+oAaIzmhLuH0L8UjGSBOcKbYr062U1VYJoYW+/6Fep4NbAsOi2UHu1nvHv46JO+FEgaQmwZ8Xy1P63GuVet5SloLqX1Z9nTPxTxVBmNGQGt0nNZ2Cf6V2REuo1TA1L6KYmxqreggxAnTSQVZSPpzlvPPL0+7NytOIU1HhIC/vd+CcghmqnHpONZQGaVshz9NojX24/Md+ArXOylkA1+58bPVZXHSIz5PM2k600Cs6HLGrICuYpFEJNaNeKIY5eNTsLuad3x601/b4Opv+ylcU0pLZEhpf0c=
  name: $MVN_PROJECT_VERSION
  draft: true
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  file:
    - db-extractor-core/target/db-extractor-core-$MVN_PROJECT_VERSION.jar
    - db-extractor-core/target/db-extractor-core-$MVN_PROJECT_VERSION-sources.jar
    - db-extractor-core/target/db-extractor-spring-$MVN_PROJECT_VERSION.jar
    - db-extractor-core/target/db-extractor-spring-$MVN_PROJECT_VERSION-sources.jar
  skip_cleanup: true
  on:
    repo: adessoSchweizAG/db-extractor
    tags: true