CREATE TABLE Customer(
	ID INTEGER PRIMARY KEY,
	FirstName VARCHAR(20),
	LastName VARCHAR(30),
	Street VARCHAR(50),
	City VARCHAR(25)
);

CREATE TABLE Invoice(
	ID INTEGER PRIMARY KEY,
	CustomerID INTEGER,
	Total DECIMAL(10, 2),
	FOREIGN KEY (CustomerId) REFERENCES Customer(ID) ON DELETE CASCADE
);

CREATE TABLE Product(
	ID INTEGER PRIMARY KEY,
	Name VARCHAR(30),
	Price DECIMAL(10, 2)
);

CREATE TABLE Item(
	ID INTEGER PRIMARY KEY,
	InvoiceID INTEGER,
	Item INTEGER,
	ProductID INTEGER,
	Quantity INTEGER,
	Cost DECIMAL(10, 2),
	UNIQUE (InvoiceID, Item),
	FOREIGN KEY (InvoiceId) REFERENCES Invoice (ID) ON DELETE CASCADE,
	FOREIGN KEY (ProductId) REFERENCES Product(ID) ON DELETE CASCADE
);
